name: netlify litedown site
description: 'Deploy then add/update PR comment'
inputs:
  netlify_auth_token:
    description: 'Netlify auth token'
    required: true
  netlify_site_id:
    description: 'Netlify site id'
    required: true
  path:
    description: 'Path to rendered site'
    required: true
    default: '.'
  pr_comment_token:
    description: 'GitHub token with issue commenting permissions'
    required: true
  tag:
    description: 'Which comment to edit, tag should be unique across actions in repo'
    required: false
    default: 'litedown docs'
  main_branch:
    description: 'branch for netlify production deployment'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Retrieve branch references, necessary for git diff main
      shell: bash
      run: |
        git switch "${GITHUB_BASE_REF}"
        git switch "${GITHUB_HEAD_REF}"
    - uses: actions/setup-node@v6
      name: setup-node https://github.com/actions/setup-node?tab=readme-ov-file#usage
    - name: Install netlify cli
      shell: bash
      run: npm install netlify-cli -g
    - name: Get netlify deploy flags
      shell: bash
      env:
        MAIN_BRANCH: ${{ inputs.main_branch }}
      run: |
        PR_OR_MAIN=$(echo "${{ github.ref_name }}" | tr / -)
        [ "$PR_OR_MAIN" == "$MAIN_BRANCH" ] && DEPLOY_FLAGS=--prod || DEPLOY_FLAGS="--alias $PR_OR_MAIN"
        echo "pr_id=$PR_OR_MAIN" >> $GITHUB_ENV
        echo "deploy_flags=$DEPLOY_FLAGS" >> $GITHUB_ENV
    - name: Deploy to netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_auth_token }}
        NETLIFY_SITE_ID: ${{ inputs.netlify_site_id }}
      shell: bash
      run: |
        netlify deploy ${{ env.deploy_flags }} --dir ${{ inputs.path }} | tee netlify.log
        NETLIFY_URL=$(grep netlify.app netlify.log | sed 's/.*https/https/' | sed 's/netlify.app.*/netlify.app/')
        echo "netlify_url=$NETLIFY_URL" >> $GITHUB_ENV
        echo env.netlify_url has a URL with no trailing /
    - name: comments.json
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PR_NUMBER: ${{ github.event.number }}
        TAG: ${{ inputs.tag }}
      shell: bash
      run: |
        curl --no-progress-meter -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10" https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments > comments.json
        echo > comment-number.txt
        echo "<!-- automatic comment for $TAG -->" > comment.md
    - name: comment-number.txt
      if: ${{ github.event_name == 'pull_request' }}
      shell: node {0}
      run: |
        fs = require('fs');
        tag = fs.readFileSync('comment.md', 'utf-8');
        content = fs.readFileSync('comments.json', 'utf-8');
        prc = JSON.parse(content);
        flist = prc.filter((o) => { return o.body.startsWith(tag); });
        if(flist.length == 0) process.exit(0);
        fs.writeFileSync('comment-number.txt', flist[0].id+"");
    - name: post diff in comment
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PR_COMMENT_TOKEN: ${{ inputs.pr_comment_token }}
        PR_NUMBER: ${{ github.event.number }}
      shell: bash
      run: |
        ISSUES_API=https://api.github.com/repos/$GITHUB_REPOSITORY/issues
        PR_API=$ISSUES_API/$PR_NUMBER/comments
        VERSION=2026-03-10
        ACCEPT=application/vnd.github+json
        COMMENT_NUMBER=$(cat comment-number.txt)
        echo ${{ env.netlify_url }} | sed "s/\(.*\)/<\1>/" >> comment.md
        cat comment.md
        git diff --name-only $GITHUB_BASE_REF | sed "s#^#<${{ env.netlify_url }}/#" | sed "s#vignettes\(/.*\).[Rrq]md#doc\1>#" | sed s=man/=manual#sec:man-= | sed 's/.Rd$/>/' | grep  '/\(manual\|doc\)' > diff.md
        cat diff.md
        if [ -s "diff.md" ]; then echo git diff shows modifications in the source file of:" >> comment.md; cat diff.md >> comment.md; fi
        cat comment.md
        if [ "$COMMENT_NUMBER" == "" ]; then CMD=$PR_API; else CMD=$ISSUES_API/comments/$COMMENT_NUMBER; fi; echo $CMD
        MD=$(sed 's/"/\\"/g' comment.md | awk '$1=$1' ORS='\\n')
        echo '{"body":"'$MD'"}' > pr-comment.json
        curl --no-progress-meter -L -H "Accept: $ACCEPT" -H "X-GitHub-Api-Version: $VERSION" -X POST -H "Authorization: Bearer $PR_COMMENT_TOKEN" $CMD -d "@pr-comment.json"
