name: netlify-simple
description: 'Deploy then add/update PR comment'
inputs:
  netlify_auth_token:
    description: 'Netlify auth token'
    required: true
  netlify_site_id:
    description: 'Netlify site id'
    required: true
  path:
    description: 'Path to rendered site'
    required: true
    default: '.'
  token:
    description: 'GitHub token with issue commenting permissions'
    required: true

runs:
  using: "composite"
  steps:
    - name: Retrieve branch references
      run: |
        git switch "${GITHUB_BASE_REF}"
        git switch "${GITHUB_HEAD_REF}"
      shell: bash
    - uses: actions/setup-node@v5
      name: setup-node https://github.com/actions/setup-node?tab=readme-ov-file#usage
      with:
        node-version: 21
    - name: https://www.npmjs.com/package/@netlify/edge-functions-bootstrap
      run: npm i @netlify/edge-functions-bootstrap -g
      shell: bash
    - name: Install netlify cli
      run: npm install netlify-cli -g
      shell: bash
    - name: Get pull request id
      run: |
        PR_OR_MAIN=$(echo "${{ github.ref_name }}" | tr / -)
        [ "$PR_OR_MAIN" == "main" ] && DEPLOY_FLAGS=--prod || DEPLOY_FLAGS="--alias $PR_OR_MAIN"
        echo "pr_id=$PR_OR_MAIN" >> $GITHUB_ENV
        echo "deploy_flags=$DEPLOY_FLAGS" >> $GITHUB_ENV
      shell: bash
    - name: Deploy to netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_auth_token }}
        NETLIFY_SITE_ID: ${{ inputs.netlify_site_id }}
      run: |
        netlify deploy ${{ env.deploy_flags }} --dir ${{ inputs.path }} | tee netlify.log
        NETLIFY_URL=$(grep netlify.app netlify.log | sed 's/.*https/https/' | sed 's/netlify.app.*/netlify.app/')
        echo "netlify_url=$NETLIFY_URL" >> $GITHUB_ENV
        echo env.netlify_url has a URL with no trailing /
      shell: bash
    - name: save diff in comment.md
      run: |
        echo ${{ env.netlify_url }} | sed "s/\(.*\)/<\1>/" > comment.md
        git diff --name-only main | sed "s#^#<https://123-merge--atime-docs.netlify.app/#" | sed "s#vignettes\(/.*\).[Rrq]md#doc\1>#" | sed s=man/=manual#sec:man-= | sed 's/.Rd$/>/' | grep  '/\(manual\|doc\)' > diff.md
        if [ -s "diff.md" ]; then echo "has modifications in these web pages:" >> comment.md; cat diff.md >> comment.md; fi
      shell: bash
    - name: post comment.md
      env:
        TOKEN: ${{ inputs.token }}
        PR_NUMBER: ${{ github.event.number }}
      run: |
        ISSUES_API=https://api.github.com/repos/$GITHUB_REPOSITORY/issues
        CURL='curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10"'
        PR_API=$ISSUES_API/$PR_NUMBER/comments
        FIRST_COMMENT_ID=$($CURL $PR_API?per_page=1 | grep '"id"' | head -1 | sed s/[^0-9]//g)
        if [ "$FIRST_COMMENT_ID" == "" ]; then CMD=$PR_API; else CMD=$ISSUES_API/comments/$FIRST_COMMENT_ID; fi; echo $CMD
        MD=$(sed 's/"/\\"/g' comment.md | awk '$1=$1' ORS='\\n')
        echo '{"body":"'$MD'"}' > pr-comment.json
        $CURL -X PATCH -H "Authorization: Bearer $TOKEN" $CMD -d "@pr-comment.json"
      shell: bash
